import { Typography } from "@mui/material";
import styled from "@emotion/styled";
import type { InferGetStaticPropsType, GetStaticProps } from "next";
import Head from "next/head";

import { Roboto } from "next/font/google";
import { Content } from "@components/Content";
import { Form } from "@components/Form";
import AxiosInstance from "@/services/axiosInstancia";
import { Brand } from "@/types";
import { useCars } from "@/hooks/useCars";
import { useEffect } from "react";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export default function Home({
  cars,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const { setupBrands } = useCars();

  useEffect(() => {
    setupBrands(cars);
  });

  return (
    <>
      <Head>
        <title> Tabela Fipe | Mobiauto </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${roboto.className}`}>
        <Content>
          <TypographyCustomized variant="h4">Tabela Fipe</TypographyCustomized>
          <TypographyCustomized variant="h5">
            Consulte o valor de um veículo de forma gratuita
          </TypographyCustomized>
          <Form />
        </Content>
      </main>
    </>
  );
}

export const getStaticProps = (async (context) => {
  const res = await AxiosInstance.get("/carros/marcas");
  const cars = Object.values(res.data) as Brand[];

  return { props: { cars } };
}) satisfies GetStaticProps<{
  cars: Brand[];
}>;
const TypographyCustomized = styled(Typography)`
  font-weight: 900;
  color: #2c2b2c;
`;
