import Head from "next/head";
import { Roboto } from "next/font/google";
import { Content } from "@components/Content";
import { Typography } from "@mui/material";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export default function Home() {
  return (
    <>
      <Head>
        <title> Tabela Fipe | Mobiauto </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${roboto.className}`}>
        <Content>
          <Typography variant="h4">Tabela Fipe</Typography>
        </Content>
      </main>
    </>
  );
}
